import type { Insight } from "@/lib/subscription";
import { GlassCard } from "@/components/glass/GlassStatic";
import { Icon } from "@/components/Icon";

const TONE = {
  up: { icon: "up", box: "bg-gain-soft text-gain", trend: "trend-up" },
  down: { icon: "down", box: "bg-loss-soft text-loss", trend: "trend-down" },
  flat: { icon: "flat", box: "bg-line text-muted", trend: "" },
} as const;

/** Plain-language reading of the numbers above. Generated by lib/subscription.ts; descriptive only. */
export function SubscriptionInsight({ insight }: { insight: Insight }) {
  const t = TONE[insight.tone];
  return (
    <GlassCard as="aside" aria-label="Subscription insight" className="enter flex gap-3 p-4 sm:gap-5 sm:p-6 lg:p-8" style={{ "--i": 3 } as React.CSSProperties}>
      <span className={`${t.trend} grid size-10 shrink-0 sm:size-12 place-items-center rounded-2xl ${t.box}`}><Icon name={t.icon} size={20} /></span>
      <div className="min-w-0">
        <p className="t-caption">Subscription insight</p>
        <h4 className="t-h3 mt-2 text-lg sm:text-xl">{insight.title}</h4>
        <div className="t-body mt-2 max-w-3xl space-y-1.5 text-[0.9375rem] sm:mt-3 sm:text-[1rem]">
          {insight.lines.map((l) => <p key={l}>{l}</p>)}
        </div>
        <p className="t-small mt-3 text-[0.75rem] text-faint sm:mt-4 sm:text-[0.875rem]">A reading of the published figures only. It is not a prediction of the listing price or investment advice.</p>
      </div>
    </GlassCard>
  );
}
